howsoai/amalgam-lang-py

- .github/workflows/build-test-package.yml
- .github/workflows/pytest.yml
TEMP_PAT is no longer needed to download amalgam release artifacts.
> 17388: Remove TEMP_PAT usage

- .github/workflows/build-test-package.yml
- MANIFEST.in
Include `version.json` in the `amalgam/lib` directory when packaging.
> 17482: Package version.json into site-packages

- .github/workflows/build-test-package.yml
Artifact upload names are essentially folders, not single artifacts. So the upload names should not have extensions in the name.
> 17585: Removes extensions from artifact upload names

- amalgam/api.py
- version.json
Added `arch` as an optional input to `Amalgam` that, if provided, will be used to generate the embedded shared object location path instead of `platform.machine()`.
Also increased the Amalgam version in `version.json`.
> 17599: Allow users to specify platform architecture

- amalgam/api.py
- amalgam/test/test_api.py
- Added check for invalid library_postfix
- Arch validation now takes into account the os
- Added platform/arch/filepath to error messages where appropriate for additional context
- Updated unit tests
> 17661: Improved error messaging when library binary is not found, MINOR

- .github/templates/version_summary.md
- .github/workflows/build.yml
- .github/workflows/get-dependency-details.yml
- .github/workflows/workflow-summary.yml
* Improves formatting of workflow summary and adds URL/SHA info
* Embeds Amalgam prerelease SemVer into `version.json` when a PR version is specified, instead of leaving irrelevant release version
* Misc. workflow code cleanup
> 17808: Adjusts workflow summary formatting

- pyproject.toml
Removes a dynamic optional dependency in `requirements-dev.in` that was removed some time ago. Dev requirements are specified already in `pyproject.toml`.
> 18641: Removes nonexistent requirements-dev.in reference in pyproject.toml

- .github/workflows/build.yml
The output of `amalgam --version` was recently changed, so we no longer need to parse out the "Amalgam version:" prefix for the version.json metadata.
> 17481: Updates version.json metadata for Amalgam

- .github/workflows/create-branch-build.yml
- .github/workflows/create-pr-build.yml
- .github/workflows/create-release-build.yml
Since other processes create tags on repos, this will ignore all tags that are not a semver release tag when determining next version.
> 18727: Updates git tag retrieval to skip non-repo tags

- .github/workflows/build.yml
Branch build code path relies on an incorrect copy of Amalgam binaries. This fixes the copy of that binary.
> 18754: Fixes bug in GitHub pipeline causing branch build failures

- .github/workflows/build.yml
Branch builds are broken because of this code. Commenting out to get pipelines working until a real fix can be implemented.
> 18754: Removes pipeline code causing branch build failures

- amalgam/api.py
* Adds quotes around Amalgam path
* Moves LOAD_ENTITY trace log to before command is run. In cases where LOAD_ENTITY fails without returning (segfault, etc), the log message will now be printed.
> 18780: Quotes Amalgam path in trace file for LOAD_ENTITY

- .github/workflows/build.yml
Windows python 3.11 tests were disabled which was causing the release job to be skipped. Re-enabling those tests.
> 18901: Re-enables windows test for py3.11

- amalgam/api.py
Adding `exist_ok=True` on the `mkdir` call that creates the directory for the tracefile.
We believe this may be the cause of some test failures where a race condition exists where multiple processes find the directory does not exist, then one creates the directory before the rest. This means that when the following processes attempt to create the directory, it already existed. Adding this flag should prevent these exceptions.
> 19165: Adds `exist_ok=True` to trace directory creation call

- amalgam/api.py
Following changes in Amalgam that fix tracefile execution to support double-quoted handle and label names, this PR adds changes to the creation of the tracefiles that ensure double quotes are escaped within handles and label names.
> 19551: Escapes double quotes in handles and label names within the tracefile

- .github/workflows/build.yml
Reversing this part of #67 since PyPi does not yet support trusted publishing from reusable workflows in different repositories.
> 19404: Reintroduces publish job as non-reusable

- .github/workflows/build.yml
Required for trusted publishing to PyPi. Followup bugfix to #68.
> 19404: Updates token permissions for release workflow

- .github/workflows/build.yml
Another follow-up to #68 to support PyPi trusted publishing.
> 19404: Adds publishing environment setting to release workflow

- amalgam/api.py
Updates the regex in `Amalgam._parse_postfix()` to work for Amalgam libraries that do not have file extensions within their name, i.e. "amalgam-mt".
> 19850: Fixes an issue when parsing the postfix of Amalgam libraries with no file extension

- amalgam/api.py
Defaults for `max_num_threads` and `sbf_datastore_enabled` are set to None. Only set them in Amalgam when they're explicitly set to non-None values.
> 20325: (B) Only set `max_num_threads` and `sbf_enabled_datastore` when explicitly set

- .github/workflows/build.yml
The step in the release workflow that publishes to PyPi often fails on the first attempt and requires a retry. However, the GitHub release happens _before_ the PyPi release currently, so someone has to go back and delete the GitHub release and tag and then retry. This reorders the steps to do the GitHub release _after_ a successful PyPi release, and also adds a retry wrapper to the PyPi release (3 attempts).
> 21160: Adds retries to PyPi publish, reorders release steps

- .github/workflows/build.yml
Follow-up to #111 which re-ordered the release steps.
> 21113: Conditions GitHub release publishing on successful PyPi upload

- amalgam/api.py
If this method is used to inject transaction-log entries, these are
not necessarily UTF-8-encoded text, and handling them as raw binary
data is correct.
> 24008: accept bytes in eval_entity_json MINOR
